--DROP TABLE IF EXISTS users;

CREATE TABLE users(
  column_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  telegram_id SMALLINT UNIQUE,
  banned BOOLEAN DEFAULT FALSE,
  join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
